
import { SmartShell } from "./mod.ts";
import { load } from "https://deno.land/std@0.204.0/dotenv/mod.ts";
const env = await load();
const shell = await new SmartShell({
    login: env['login'],
    password: env['password'],
    club_id: Number(env['club_id'])
})

console.log('[[[call]]]')
console.log(await shell.api.call(`
  query UserClubs {
      userClubs {
            id
            name
            address
            tariffName
            workShiftStatus
            permitted
            operatorFirstName
            operatorLastName
      }
  }`))
console.log('[[[getAccessToken]]]')
console.log(await shell.api.getAccessToken())
console.log('[[[getClubs]]]')
console.log(await shell.api.getClubs())
console.log('[[[getMe]]]')
console.log(await shell.api.getMe())
console.log('[[[getGoods]]]')
console.log(await shell.api.getGoods())
console.log('[[[getPromocodes]]]')
console.log(await shell.api.getPromocodes())
console.log('[[[getFullReport]]]')
console.log(await shell.api.getFullReport())
 console.log(await shell.api.getFullReport('2023-07-20', 'CURRENT', 'TODAY', 'CURRENT'))
 console.log(await shell.api.getFullReport('2023-07-20', 'CURRENT'))
console.log('[[[getServices]]]')
console.log(await shell.api.getServices())
console.log('[[[getShortcuts]]]')
console.log(await shell.api.getShortcuts())
console.log('[[[getTariffs]]]')
console.log(await shell.api.getTariffs())
console.log('[[[getUsers]]]')
console.log(await shell.api.getUsers())
  console.log(await shell.api.getUsers(2))
console.log('[[[getAllUsers]]]')
console.log(await shell.api.getAllUsers(true))
console.log('[[[getUsersByQuery]]]')
console.log(await shell.api.getUsersByQuery('XL Sof'))
 console.log(await shell.api.getUsersByQuery('9999'))
 console.log(await shell.api.getUsersByQuery('Torshin'))
console.log('[[[getPayments]]]')
console.log(await shell.api.getPayments('a50c445f-3d8b-4800-98f3-fcd1cbf25eb7'))
console.log('[[[getShifts]]]')
console.log(await shell.api.getShifts())
console.log('[[[getActiveShift]]]')
console.log(await shell.api.getActiveShift())
console.log('[[[getTasks]]]')
console.log(await shell.api.getTasks())
console.log('[[[getVersion]]]')
console.log(await shell.api.getVersion())
console.log('[[[getCurrency]]]')
console.log(await shell.api.getCurrency())
console.log('[[[getHosts]]]')
console.log(await shell.api.getHosts())
console.log('[[[getHosts]]]')
console.log(await shell.api.getHosts())
console.log('[[[getAccessToken]]]')
console.log(await shell.getAccessToken())
console.log('[[[getClubs]]]')
console.log(await shell.getClubs())
console.log('[[[getClubById]]]')
console.log(await shell.getClubById(1234))
console.log('[[[getGoods]]]')
console.log(await shell.getGoods())
console.log('[[[getGoodByName]]]')
console.log(await shell.getGoodByName('Cola'))
console.log('[[[getGoodByBarcode]]]')
console.log(await shell.getGoodByBarcode('501234576421'))
console.log('[[[getServices]]]')
console.log(await shell.getServices())
console.log('[[[getServiceByName]]]')
console.log(await shell.getServiceByName('Hookah'))
console.log('[[[getServiceByBarcode]]]')
console.log(await shell.getServiceByBarcode('501234576421'))
console.log('[[[getPromocodes]]]')
console.log(await shell.getPromocodes())
console.log('[[[getPromocodeByName]]]')
console.log(await shell.getPromocodeByName('SALE50'))
console.log('[[[getStat]]]')
console.log(await shell.getStat())
 console.log(await shell.getStat('2023-07-20', 'CURRENT', 'TODAY', 'CURRENT'))
 console.log(await shell.getStat('2023-07-20', 'CURRENT'))
console.log('[[[getGoodsStat]]]')
console.log(await shell.getGoodsStat())
 console.log(await shell.getGoodsStat('2023-07-20', 'CURRENT', 'TODAY', 'CURRENT'))
 console.log(await shell.getGoodsStat('2023-07-20', 'CURRENT'))
console.log('[[[getServicesStat]]]')
console.log(await shell.getServicesStat())
 console.log(await shell.getServicesStat('2023-07-20', 'CURRENT', 'TODAY', 'CURRENT'))
 console.log(await shell.getServicesStat('2023-07-20', 'CURRENT'))
console.log('[[[getOrdersStat]]]')
console.log(await shell.getOrdersStat())
 console.log(await shell.getOrdersStat('2023-07-20', 'CURRENT', 'TODAY', 'CURRENT'))
 console.log(await shell.getOrdersStat('2023-07-20', 'CURRENT'))
console.log('[[[getSeancesStat]]]')
console.log(await shell.getSeancesStat())
 console.log(await shell.getSeancesStat('2023-07-20', 'CURRENT', 'TODAY', 'CURRENT'))
 console.log(await shell.getSeancesStat('2023-07-20', 'CURRENT'))
console.log('[[[getDepositStat]]]')
console.log(await shell.getDepositStat())
 console.log(await shell.getDepositStat('2023-07-20', 'CURRENT', 'TODAY', 'CURRENT'))
 console.log(await shell.getDepositStat('2023-07-20', 'CURRENT'))
console.log('[[[getMoneyStat]]]')
console.log(await shell.getMoneyStat())
 console.log(await shell.getMoneyStat('2023-07-20', 'CURRENT', 'TODAY', 'CURRENT'))
 console.log(await shell.getMoneyStat('2023-07-20', 'CURRENT'))
console.log('[[[getRevenueStat]]]')
console.log(await shell.getRevenueStat())
 console.log(await shell.getRevenueStat('2023-07-20', 'CURRENT', 'TODAY', 'CURRENT'))
 console.log(await shell.getRevenueStat('2023-07-20', 'CURRENT'))
console.log('[[[getApps]]]')
console.log(await shell.getApps())
console.log('[[[getAppByName]]]')
console.log(await shell.getAppByName('Discord'))
console.log('[[[getPopularApps]]]')
console.log(await shell.getPopularApps())
console.log('[[[getGames]]]')
console.log(await shell.getGames())
console.log('[[[getGameByName]]]')
console.log(await shell.getGameByName('Dota 2'))
console.log('[[[getPopularGames]]]')
console.log(await shell.getPopularGames())
console.log('[[[getTariffs]]]')
console.log(await shell.getTariffs())
console.log('[[[getTariffByName]]]')
console.log(await shell.getTariffByName('Night'))
console.log('[[[getActiveTariffs]]]')
console.log(await shell.getActiveTariffs())
console.log('[[[getActiveUserTariffs]]]')
console.log(await shell.getActiveUserTariffs())
console.log('[[[getConnectionUser]]]')
console.log(await shell.getConnectionUser())
console.log('[[[getUsersByQuery]]]')
console.log(await shell.getUsersByQuery('XL Sof'))
 console.log(await shell.getUsersByQuery('9999'))
 console.log(await shell.getUsersByQuery('Torshin'))
console.log('[[[getUserByPhone]]]')
console.log(await shell.getUserByPhone('79999999999'))
console.log('[[[getUserByHostName]]]')
console.log(await shell.getUserByHostName('PC-24'))
console.log('[[[getPaymentsByPhone]]]')
console.log(await shell.getPaymentsByPhone('79999999999'))
console.log('[[[getCardPaymentsByPhone]]]')
console.log(await shell.getCardPaymentsByPhone('79999999999'))
console.log('[[[getCashPaymentsByPhone]]]')
console.log(await shell.getCashPaymentsByPhone('79999999999'))
console.log('[[[getDepositPaymentsByPhone]]]')
console.log(await shell.getDepositPaymentsByPhone('79999999999'))
console.log('[[[getBonusPaymentsByPhone]]]')
console.log(await shell.getBonusPaymentsByPhone('79999999999'))
console.log('[[[getShifts]]]')
console.log(await shell.getShifts())
console.log('[[[getShiftsByPhone]]]')
console.log(await shell.getShiftsByPhone('79999999999'))
console.log('[[[getShiftById]]]')
console.log(await shell.getShiftById(639126))
console.log('[[[getLastShift]]]')
console.log(await shell.getLastShift())
console.log('[[[getLastShiftByPhone]]]')
console.log(await shell.getLastShiftByPhone('79999999999'))
console.log('[[[getActiveShift]]]')
console.log(await shell.getActiveShift())
console.log('[[[getTasks]]]')
console.log(await shell.getTasks())
console.log('[[[getFinishedTasks]]]')
console.log(await shell.getFinishedTasks())
console.log('[[[getActiveTasks]]]')
console.log(await shell.getActiveTasks())
console.log('[[[getVersion]]]')
console.log(await shell.getVersion())
console.log('[[[getCurrency]]]')
console.log(await shell.getCurrency())
console.log('[[[getHosts]]]')
console.log(await shell.getHosts())
console.log('[[[getHostByName]]]')
console.log(await shell.getHostByName('PC-24'))
console.log('[[[getHostInfoByName]]]')
console.log(await shell.getHostInfoByName('PC-24'))
console.log('[[[getHostCountersByName]]]')
console.log(await shell.getHostCountersByName('PC-24'))
console.log('[[[getHostDisksByName]]]')
console.log(await shell.getHostDisksByName('PC-24'))
console.log('[[[getHostLastCommentByName]]]')
console.log(await shell.getHostLastCommentByName('PC-24'))
console.log('[[[getHostIdByName]]]')
console.log(await shell.getHostIdByName('PC-24'))
console.log('[[[getFreeHosts]]]')
console.log(await shell.getFreeHosts())
console.log('[[[getFreeHostsCount]]]')
console.log(await shell.getFreeHostsCount())
console.log('[[[getTimestamp]]]')
console.log(await shell.utils.getTimestamp()) // Current time and date stamp
 console.log(await shell.utils.getTimestamp('2023-10-30')) // Same time at 30 october 2023
 console.log(await shell.utils.getTimestamp('TODAY', '20:00:00')) // Today at 20:00
 console.log(await shell.utils.getTimestamp('TOMORROW')) // Tomorrow at same time
 console.log(await shell.utils.getTimestamp('TOMORROW', 'CURRENT', 3)) // Tomorrow at same time with +3 from system timezone
 console.log(await shell.utils.getTimestamp('TOMORROW', 'CURRENT', -5)) // Tomorrow at same time with -5 from system timezone
console.log('[[[getCurrent]]]')
console.log(await shell.utils.getCurrent(0)) // Current time and date stamp with 0 timezone offset
 console.log(await shell.utils.getCurrent(3)) // Current time and date stamp with +3 timezone offset
 console.log(await shell.utils.getCurrent(3, true)) // Current time and tomorrow date stamp with +3 timezone offset